version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    restart: unless-stopped
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db:5432/horilla"
      DB_NAME: "horilla"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_HOST: "db"
      DB_PORT: "5432"
    command: >
      sh -c "python3 manage.py makemigrations && 
             python3 manage.py migrate && 
             python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./horilla:/app/horilla
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-bullseye
    environment:
      POSTGRES_DB: horilla
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - horilla-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  horilla-data:
